# 公開するページのURL
baseURL = "https://pome-ta.github.io/pome-ta_hugo-blog"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true
# サマリの長さ
summaryLength = 108

# ブログのタイトル
title = "pome-ta_hugo_blog"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "pome-ta"
    bio = "よろしくお願いします。"
    avatar = "img/avatar.jpg"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "pome-ta"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#800000"

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "pome_ta93"
  github = "pome-ta"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

